# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/c9s/goprocinfo"

[[constraint]]
  branch = "master"
  name = "github.com/deniswernert/go-fstab"

[[constraint]]
  name = "github.com/segmentio/go-log"
  version = "1.9.0"

[[constraint]]
  name = "github.com/statsd/client"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/statsd/client-interface"

[[constraint]]
  branch = "master"
  name = "github.com/statsd/client-namespace"

[[constraint]]
  name = "github.com/tj/docopt"
  version = "1.0.0"

[[constraint]]
  name = "github.com/tj/go-gracefully"
  version = "2.0.1"

[prune]
  go-tests = true
  unused-packages = true
